version: '3.9'
services:
  postgres:
    container_name: postgres_containermicro
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=nestjsauth
      - POSTGRES_PASSWORD=nestjsauth
      - POSTGRES_DB=nestjsauth
    ports:
      - '5432:5432'
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql
