export enum FoodSort {
  NAME_ASC = 'NAME_ASC',
  NAME_DESC = 'NAME_DESC',
  PRICE_ASC = 'PRICE_ASC',
  PRICE_DESC = 'PRICE_DESC',
  CREATEDAT_ASC = 'CREATED_AT_ASC',
  CREATEDAT_DESC = 'CREATED_AT_DSC',
}
